[project]
name = "blogpostapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.116.0",
    "requests>=2.32.4",
    "streamlit>=1.46.1",
]
